project_name: statuspage

release:
  name_template: "Version {{.Version}}"
  github:
    owner: kfsoftware
    name: statuspage

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: statuspage
    binary: statuspage
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Tag}}
    flags:
      - -trimpath

archives:
  - format: binary
    allow_different_binary_count: true

dockers:
  - # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/kfsoftware/statuspage-api:{{ .Tag }}"
      - "ghcr.io/kfsoftware/statuspage-api:v{{ .Major }}"
      - "ghcr.io/kfsoftware/statuspage-api:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/kfsoftware/statuspage-api:latest"

    extra_files:
      - LICENSE
      - README.md
