// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"time"
)

type Check interface {
	IsCheck()
}

type CheckExecution struct {
	ID            string    `json:"id"`
	ExecutionTime time.Time `json:"executionTime"`
	Message       string    `json:"message"`
	ErrorMsg      string    `json:"errorMsg"`
	Status        string    `json:"status"`
}

type CheckUptime struct {
	Uptime24h float64 `json:"uptime24h"`
	Uptime7d  float64 `json:"uptime7d"`
	Uptime30d float64 `json:"uptime30d"`
}

type CreateHTTPCheckInput struct {
	Name       string `json:"name"`
	Namespace  string `json:"namespace"`
	Frecuency  string `json:"frecuency"`
	URL        string `json:"url"`
	StatusCode int    `json:"statusCode"`
}

type CreateICMPCheckInput struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	Frecuency string `json:"frecuency"`
	Address   string `json:"address"`
}

type CreateStatusPageInput struct {
	Name       string   `json:"name"`
	Namespace  string   `json:"namespace"`
	Title      string   `json:"title"`
	CheckSlugs []string `json:"checkSlugs"`
}

type CreateTCPCheckInput struct {
	Name      string `json:"name"`
	Namespace string `json:"namespace"`
	Frecuency string `json:"frecuency"`
	Address   string `json:"address"`
}

type CreateTLSCheckInput struct {
	Name      string  `json:"name"`
	Namespace string  `json:"namespace"`
	Frecuency string  `json:"frecuency"`
	Address   string  `json:"address"`
	RootCAs   *string `json:"rootCAs"`
}

type DeleteResponse struct {
	ID string `json:"id"`
}

type Namespace struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type PollResult struct {
	Took int `json:"took"`
}
